### ISSUE TITLE
The wav encoding doesn't work.

### ISSUE THREAD

**Issue by e-rasvet** [kaliatech/web-audio-recording-tests-simpler#2]
Hello!

I founded cross browser mp3 encoding, and found great sample with your code here:
https://kaliatech.github.io/web-audio-recording-tests/dist/index.html#/
But when I tried to implement it in my code with your web-audio-recording-tests-simpler I found that wav encoder didn't work, the recording was always saved in *.webm  format. 
I've added console logs to be sure about it:

```
function encode (buffer) {
  console.log("encode starting")
...
function dump (sampleRate) {
  console.log("dump starting")
...
onmessage = function (e) {
  console.log("message: " + e.data[0])
```

and yes, these functions aren't called by script, and file encoder-wav-worker.js isn't used. 

Is it possible to fix encoding to wav (using this example I can try to make mp3 encoding).

Thanks!

**Comment by e-rasvet** [comment]
I found how to fix this issue for me. 

```
      usingMediaRecorder: false,
      //usingMediaRecorder: typeof window.MediaRecorder !== 'undefined',
```

When usingMediaRecorder is false, the code working well.

**Comment by Todd1561** [comment]
Thanks @e-rasvet for posting this, been scratching my head for a while
